<?php
/**
 *
* Copyright © Magento. All rights reserved.
* See COPYING.txt for license details.
*/
namespace Hummingbird\US5\Controller\Adminhtml\Action;

/**
 * * Class HelloWorld
* @package Hummingbird\US5\Controller\Adminhtml\Action
*/
class Helloworld extends \Magento\Backend\App\Action
{
 /**
 * execute method
 */
 public function execute()
 {
 $this->_redirect('catalog/category/edit/id/2');
 }

 /**
 * Link must be generated by server side
 * It's only for education purpose!
 *
 * @return bool
 */
 public function _processUrlKeys()
 {
 return true;
 }
} 